---
title: "Vis part 2"
author: "Longyi Zhao"
date: "2023-10-03"
output: github_document 
---

```{r}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

this results in a dataframe with `r nrow(weather_df)` observations on `r ncol(weather_df)` variables

## same plot from last time 

```{r}
weather_df |>
  # filter (tmax >= 20, tmax <=30)
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot", 
    x = "min daily temp (Degree C)", 
    y = "max daily temp",
    color = "location", 
    caption = "max vs min daily temperature in three locations"
  ) +
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c( "-15C", "0", "15C")
  ) +
  scale_y_continuous(
    position = "right", 
    # limits = c(0,30) #zoom in 
    trans = "sqrt"
  )
```

what about color
```{r}
weather_df |>
  # filter (tmax >= 20, tmax <=30)
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot", 
    x = "min daily temp (Degree C)", 
    y = "max daily temp",
    color = "location", 
    caption = "max vs min daily temperature in three locations"
  ) +
  # scale_color_hue(h = c(150,300)) # change color 
  viridis::scale_color_viridis(discrete = TRUE) # this is encouraged
```

## Themes

theme_bw change background to blk and white, order matters
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot", 
    x = "min daily temp (Degree C)", 
    y = "max daily temp",
    color = "location", 
    caption = "max vs min daily temperature in three locations"
  ) +
  viridis::scale_color_viridis(discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "bottom") 
```

## data argument 
```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth()


nyc_weather_df = 
  weather_df |>
  filter(name == "CentralPark_NY")

hawaii_weather_df =
  weather_df |>
  filter(name == "Molokai_HI")


ggplot(nyc_weather_df, aes(x=date, y=tmax, color = name))+
  geom_point() +
  geom_line(data = hawaii_weather_df)
```

## patchwork

```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax, color = name)) +
  geom_point() +
  facet_grid(.~name)
```

```{r}
ggp_temp_scatter = 
  weather_df |>
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5)

ggp_prcp_density = 
  weather_df |>
  filter(prcp>25) |>
  ggplot(aes(x=prcp, fill = name)) +
  geom_density(alpha = 0.5) +
  theme(legend.position = "bottom")

ggp_temp_scatter + ggp_prcp_density #cannot add
```


## data manipulation 
fct_relevel: change the order of data
```{r}
weather_df |>
  mutate(
    name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))
  ) |>
  ggplot(aes(x=name, y=tmax))+
  geom_boxplot()

# fct_reorder: order by the tmaz value
weather_df |>
  mutate(
    name = fct_reorder(name,tmax)
  ) |>
  ggplot(aes(x=name, y=tmax, fill = name))+
  geom_violin()
```


easier to start by first sketch on paper: what i want 
```{r}
litter_data = 
  read_csv("./data/FAS_litters.csv") |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

pup_data = 
  read_csv("./data/FAS_pups.csv") |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"))

fas_df = 
  left_join(pup_data, litter_data, by = "litter_number")


fas_df |> 
  select(sex, dose, day_of_tx, pd_ears:pd_walk) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome", 
    values_to = "pn_day") |> 
  drop_na() |> 
  mutate(outcome = forcats::fct_reorder(outcome, pn_day, median)) |> 
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() + 
  facet_grid(day_of_tx ~ outcome)

```


