---
title: "Vis part 1"
author: "Longyi Zhao"
date: "2023-09-28"
output: github_document 
---
```{r}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


lets make a plot 

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax)) +
  geom_point()
```

pipes and stuff

```{r, eval = FALSE}
weather_df |> 
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point() 
```


## fancy plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth() +
  facet_grid(. ~name)
```

try assigning a specific color 

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x=date, y=tmax)) +
  geom_point(color = "blue")
```

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x=date, y=tmax, color = name))+
  geom_point(alpha = 0.7, size = 0.5) # alpha is the transparency, size is the point size 
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y=tmax)) + 
  geom_hex()
```

histogram 
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(alpha = 0.3, position = "dodge")
```


boxplot
```{r}
ggplot(weather_df, aes(y = tmax, x=name))+
  geom_boxplot()
```

